### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by s265452** [dirk-thomas/vcstool#234]
Hi everyone,
I wish to implement your planner.
I followed your instructions:

mkdir -p catkin_ws/src
cd catkin_ws/src
git clone https://github.com/JeroenDM/elion.git
rosdep install --from-paths . --ignore-src

Here that's all right, but when I try to

vcs import < elion/test_dependencies.repos

I've these problems

~/catkin_ws/src$ vcs import < elion/test_dependencies.repos
Traceback (most recent call last):
File "/usr/local/bin/vcs", line 11, in
load_entry_point('vcstool==0.3.0', 'console_scripts', 'vcs')()
File "/home/francesco/.local/lib/python2.7/site-packages/pkg_resources/init.py", line 489, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/home/francesco/.local/lib/python2.7/site-packages/pkg_resources/init.py", line 2852, in load_entry_point
return ep.load()
File "/home/francesco/.local/lib/python2.7/site-packages/pkg_resources/init.py", line 2443, in load
return self.resolve()
File "/home/francesco/.local/lib/python2.7/site-packages/pkg_resources/init.py", line 2449, in resolve
module = import(self.module_name, fromlist=['name'], level=0)
File "/usr/local/lib/python2.7/dist-packages/vcstool/commands/init.py", line 1, in
from .branch import BranchCommand
File "/usr/local/lib/python2.7/dist-packages/vcstool/commands/branch.py", line 6, in
from .command import Command
File "/usr/local/lib/python2.7/dist-packages/vcstool/commands/command.py", line 6, in
from vcstool.executor import execute_jobs
File "/usr/local/lib/python2.7/dist-packages/vcstool/executor.py", line 31
file=stdout)
^
SyntaxError: invalid syntax

https://github.com/JeroenDM/elion/issues/11#issuecomment-963483583

JeroenDM says: "The default version of vcs tools does not support python2 anymore."

Can you help me??? How can I do that?

Thank you in advance

**Comment by dirk-thomas** [comment]
I don't know which platform you are using. Assuming it is Ubuntu or Debian based, you should uninstall the current Python 2 version of `vcstool` and follow the instructions how to install the Python 3 package in the README: https://github.com/dirk-thomas/vcstool#how-to-install-vcstool
