### ISSUE TITLE
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

### ISSUE THREAD

**Issue by MarcoDotIO** [dirk-thomas/vcstool#278]
This is the error I got when running the command line VCSTools:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/vcs", line 5, in <module>
    from vcstool.commands.vcs import main
  File "/opt/homebrew/lib/python3.13/site-packages/vcstool/commands/vcs.py", line 3, in <module>
    from vcstool.commands.help import get_entrypoint
  File "/opt/homebrew/lib/python3.13/site-packages/vcstool/commands/help.py", line 4, in <module>
    from pkg_resources import load_entry_point
  File "/opt/homebrew/lib/python3.13/site-packages/pkg_resources/__init__.py", line 2172, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

Specifications for Context:
- Python version - 3.13
- Device - MacBook Pro, M3 Max, macOS Sequoia 15.1

If there are any other specifications needed for debugging, let me know.

**Comment by MarcoDotIO** [comment]
Update: Problem is resolved, just:
- Downgrade to 3.12 using pyenv
- Use `pip install vcstool`, since one tutorial had it installed differently.
